#!/usr/bin/bash

#Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name."
    exit 1
fi

echo "Deleted Succesfully."

aws s3api delete-bucket --bucket $1 --region eu-north-1 